name: Tests
on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-12', 'macos-14', 'macos-14-large' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        uname -a
        pkgutil --pkg-info com.apple.pkg.CLTools_Executables
        xcode-select -p
        clang —version
        #clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        #./newbufnocopy
