name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test-macos-12:
    name: tests(macos-12)
    runs-on: macos-12
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        uname -a
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        ./newbufnocopy

  test-macos-14:
    name: tests(macos-14)
    runs-on: macos-14
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        uname -a
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        ./newbufnocopy

  test-macos-13:
    name: tests(macos-13)
    runs-on: macos-13
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        uname -a
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        ./newbufnocopy

  test-macos-13-arm64:
    name: tests(macos-13-arm64)
    runs-on: macos-13-xlarge
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Run Example
      run: | 
        uname -a
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        ./newbufnocopy
