name: Tests
on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Install Clang 14.0.3
      run: |
        brew install llvm@14
        echo 'export PATH="/usr/local/opt/llvm@14/bin:$PATH"' >> $GITHUB_ENV
        echo 'export LDFLAGS="-L/usr/local/opt/llvm@14/lib"' >> $GITHUB_ENV
        echo 'export CPPFLAGS="-I/usr/local/opt/llvm@14/include"' >> $GITHUB_ENV
    - name: Run Example
      run: | 
        uname -a
        pkgutil --pkg-info com.apple.pkg.CLTools_Executables
        xcode-select -p
    - name: Verify clang installation
      run: clang --version
    - name: compile code using clang
      run: | 
        clang -framework CoreGraphics -framework Foundation -framework Metal newbufnocopy.m -o newbufnocopy
        ./newbufnocopy
